version: '3.1'

services:

  db:
     build: ./serverdb
     restart: always
     environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "sncf"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "root"
     expose:
        - "3306"
     networks:
        - backend

  php:
     depends_on:
        - db
     build: ./serverapp
     ports:
       - 8090:80
     networks:
       - backend

networks:
  backend:
    driver: bridge
