---

apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  selector:
     app: db
  ports:
     - port: 3306
       protocol: TCP
       targetPort: 3306


---

apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: ClusterIP
  selector:
    app: apache
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3306

